### ISSUE TITLE
Подогнать рычаг переключение передач

### ISSUE THREAD

**Issue by dragolite17** [Son1kXDev/car-game#10]

**Comment by Son1kXDev** [comment]
_Commit [dacc30f](https://github.com/Son1kXDev/car-game/commit/dacc30f3d7b33e71432b8f8216b7dde4a0065632)_
Сделал метку рычага переключения передач на одном уровне с буквенным обозначением передачи.

![Image](https://github.com/Son1kXDev/car-game/assets/106654105/b067ed0b-d2df-441b-b5f4-ef819a3676b8)
![Image](https://github.com/Son1kXDev/car-game/assets/106654105/fad8a0e8-89af-42e2-9b53-3dabb12053d5)

**Comment by Son1kXDev** [comment]
@dragolite17 передаю в тест
