### ISSUE TITLE
Сделать интерфейс для меню паузы

### ISSUE THREAD

**Issue by Son1kXDev** [Son1kXDev/car-game#11]
Интерфейс следующего типа:
_Заголовок "Пауза/Pause".
Кнопка "Продолжить/Continue"
Кнопка "Настройки/Settings"
Кнопка "Выход/Quit"_

Меню настроек такое же как и меню настроек в главном меню (возможно с некоторыми ограничениями, например без возможности смены языка)

Кнопка выход отправляет в меню гаража, кнопка продолжить выключает паузу и закрывает попап.

- [x] #17

**Comment by dragolite17** [comment]
![Image](https://github.com/Son1kXDev/car-game/assets/119760537/11be8d91-73d7-4979-906b-19ced4b63d51)

главная страница меню паузы готова

**Comment by dragolite17** [comment]
[PausePopup.zip](https://github.com/Son1kXDev/car-game/files/11566494/PausePopup.zip)
спрайты к меню паузы

**Comment by dragolite17** [comment]
![Image](https://github.com/Son1kXDev/car-game/assets/119760537/0e37690e-ae97-4772-a7ef-8c18c5b81175)

только попап
