### ISSUE TITLE
Сделать новый интерфейс всплывающих окон

### ISSUE THREAD

**Issue by Son1kXDev** [Son1kXDev/car-game#2]
![Image](https://github.com/Son1kXDev/car-game/assets/106654105/8354d248-9769-4238-ae4e-399c0724c817)
![Image](https://github.com/Son1kXDev/car-game/assets/106654105/4da1c530-69d2-44e9-a38d-cc90d7b17166)
![Image](https://github.com/Son1kXDev/car-game/assets/106654105/179f295b-b0e2-47b4-872a-c972aee16f62)
![Image](https://github.com/Son1kXDev/car-game/assets/106654105/d28e0d31-5cae-4a57-9139-acac4156c882)
![Image](https://github.com/Son1kXDev/car-game/assets/106654105/0d6bea6f-4646-4b9b-9944-785f98971e08)
![Image](https://github.com/Son1kXDev/car-game/assets/106654105/a9ec02a8-41df-41b1-85a4-d067627c2125)

**Comment by Son1kXDev** [comment]
Дополнение к попапу настроек:

- Надпись "Настройки/Settings"
- Кнопка "Графика/Graphics"
- Кнопка "Звук/Audio"
- Кнопка "Интерфейс/Interface (UI)"
- Кнопка "Назад/Back"

Сделать в стиле попапа паузы #11

**Comment by dragolite17** [comment]
[SettingsTextures.zip](https://github.com/Son1kXDev/car-game/files/11581633/SettingsTextures.zip)

дополнение концептов и текстур для раздела настроек

**Comment by dragolite17** [comment]
[GameplayMiniPopupInterface.zip](https://github.com/Son1kXDev/car-game/files/11582641/GameplayMiniPopupInterface.zip)

для попупов предупреждений

**Comment by Son1kXDev** [comment]
Сделаны:

- [x] Всплывающие окна
- [x] Настройки
- [x] Пауза
- [x] Частицы для настроек

![Image](https://github.com/Son1kXDev/car-game/assets/106654105/5ab5afe2-69b5-46ab-9775-5edcba541b99)
![Image](https://github.com/Son1kXDev/car-game/assets/106654105/d069ff4d-b8c0-4337-9281-bbc58690b87b)
![Image](https://github.com/Son1kXDev/car-game/assets/106654105/721c2ead-d680-4d51-aabb-ec4abf04e7ee)
![Image](https://github.com/Son1kXDev/car-game/assets/106654105/0008628f-59a9-4028-9bb2-a9050ff2a256)
![Image](https://github.com/Son1kXDev/car-game/assets/106654105/e9fb6480-8b98-4e89-b718-901c820421d6)

**Comment by dragolite17** [comment]
[Chekpup.zip](https://github.com/Son1kXDev/car-game/files/11619600/Chekpup.zip)

для финиша и чекпоинтов на момент беты
